### ISSUE TITLE
Exception about malware_hunt.py calling OPcacheDisassembler

### ISSUE THREAD

**Issue by zjuchenyuan** [GoSecure/php7-opcache-override#4]
```
Traceback (most recent call last):
  File "./opcache_malware_hunt.py", line 381, in <module>
    (file_name, report) = create_diff_report(new_cache_file, file, opcache_files[idx], "Source Code", "Cache", is_64_bit)
  File "./opcache_malware_hunt.py", line 250, in create_diff_report
    disassembled_1 = OPcacheDisassembler(is_64_bit).disassemble(file1).split("\n")
TypeError: __init__() takes exactly 3 arguments (2 given)
```

I simply changed `opcache_disassembler.py`, by adding a default value for `color_output` of `__init__` function, I skipped this problem:

```
class OPcacheDisassembler():
    def __init__(self, is_64_bit, color_output=None):
```

**Comment by Corb3nik** [comment]
Sorry for the delay, I added the default value to `color_output` to fix the issue.

Thanks!
